# Generated by Django 5.1.6 on 2025-02-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
